part of '../romanized_translation_engine.dart';

/// Phonetic lookup tables and default poetic glossary for Romanized translation.
class RomanizedPhoneticTables {
  RomanizedPhoneticTables._();

  static const Map<String, String> vowels = {
    'अ': 'a',
    'आ': 'aa',
    'इ': 'i',
    'ई': 'ee',
    'उ': 'u',
    'ऊ': 'oo',
    'ऋ': 'ri',
    'ए': 'e',
    'ऐ': 'ai',
    'ओ': 'o',
    'औ': 'au',
    'अं': 'an',
    'अः': 'ah',
    'ऑ': 'o',
    'ऍ': 'e',
  };

  static const Map<String, String> matras = {
    'ा': 'aa',
    'ि': 'i',
    'ी': 'ee',
    'ु': 'u',
    'ू': 'oo',
    'ृ': 'ri',
    'े': 'e',
    'ै': 'ai',
    'ो': 'o',
    'ौ': 'au',
    'ं': 'n',
    'ँ': 'n',
    'ः': 'h',
    '़': '',
    '्': '',
  };

  static const Set<String> nasalMarks = {'ं', 'ँ', 'ः'};

  static const Map<String, String> nuktaConsonants = {
    'क': 'q',
    'ख': 'kh',
    'ग': 'gh',
    'ज': 'z',
    'ड': 'r',
    'ढ': 'rh',
    'फ': 'f',
  };

  static const Map<String, String> consonants = {
    'क': 'k',
    'ख': 'kh',
    'ग': 'g',
    'घ': 'gh',
    'ङ': 'ng',
    'च': 'ch',
    'छ': 'chh',
    'ज': 'j',
    'झ': 'jh',
    'ञ': 'ny',
    'ट': 't',
    'ठ': 'th',
    'ड': 'd',
    'ढ': 'dh',
    'ण': 'n',
    'त': 't',
    'थ': 'th',
    'द': 'd',
    'ध': 'dh',
    'न': 'n',
    'प': 'p',
    'फ': 'ph',
    'ब': 'b',
    'भ': 'bh',
    'म': 'm',
    'य': 'y',
    'र': 'r',
    'ल': 'l',
    'व': 'v',
    'श': 'sh',
    'ष': 'sh',
    'स': 's',
    'ह': 'h',
    'क़': 'q',
    'ख़': 'kh',
    'ग़': 'gh',
    'ज़': 'z',
    'ड़': 'r',
    'ढ़': 'rh',
    'फ़': 'f',
    'क्ष': 'ksh',
    'त्र': 'tr',
    'ज्ञ': 'gyan',
    'श्र': 'shr',
  };

  static const Map<String, String> defaultEnglishGlossary = {
    'dil': 'heart / soul',
    'ishq': 'passion / deep love',
    'pyaar': 'love',
    'pyar': 'love',
    'mohabbat': 'affection / love',
    'zindagi': 'life',
    'khuda': 'god / almighty',
    'rabba': 'lord / god',
    'rab': 'lord',
    'naina': 'eyes',
    'aankhen': 'eyes',
    'dard': 'pain / longing',
    'sukoon': 'peace / solace',
    'khushi': 'happiness',
    'gham': 'sorrow / grief',
    'aansu': 'tears',
    'intezaar': 'waiting / longing',
    'armaan': 'desires / wishes',
    'sapna': 'dream',
    'khwab': 'dream / vision',
    'tamanna': 'wish / yearning',
    'chahat': 'longing / affection',
    'dhadkan': 'heartbeat',
    'saansein': 'breaths',
    'hawayein': 'winds / breezes',
    'kesariya': 'saffron / beloved',
    'raat': 'night',
    'din': 'day',
    'subah': 'morning',
    'shaam': 'evening',
    'chand': 'moon',
    'sitara': 'star',
    'suraj': 'sun',
    'aasman': 'sky',
    'baarish': 'rain',
    'hawa': 'breeze',
    'lamha': 'moment',
    'khamoshi': 'silence',
    'awaaz': 'voice / calling',
    'sanam': 'beloved',
    'yaar': 'friend / lover',
    'jaaneman': 'sweetheart',
    'jaan': 'life / beloved',
    'humsafar': 'companion / soulmate',
    'mehboob': 'beloved',
    'piya': 'beloved',
    'manwa': 'my heart',
    'jiyara': 'my soul',
    'manzil': 'destination',
    'safar': 'journey',
    'raah': 'path',
    'dua': 'prayer / blessing',
    'kismat': 'destiny / fate',
    'naseeb': 'fate',
    'rooh': 'soul / spirit',
  };
}
