class LocalizationStringsNorth {
  static const Map<String, Map<String, String>> values = {
    'en': {
      'lang_name': 'English',
      'app_name': 'Noctra',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'search_explore': 'Search & Explore',
      'library_title': 'Library & Storage',
      'ai_studio_title': 'AI Sound Studio',
      'top_charts': 'Global Charts',
      'create_folder': 'Create New Folder',
      'delete_folder': 'Delete Folder',
      'settings': 'Settings & Storage',
      'party_mode': 'SyncCast Party Mode',
      'lossless_quality': 'Master 320k Ready',
      'recently_played': 'Recently Played',
      'equalizer': 'Equalizer FX',
      'developer_suite': 'Developer Suite',
      'check_updates': 'Check for Updates',
      'theme': 'Theme',
      'language': 'Language / भाषा',
      'home': 'Home',
      'search': 'Search',
      'library': 'Library',
      'ai_studio': 'AI Studio',
      'favorites': 'Favorites',
      'downloads': 'Downloads',
      'all_songs': 'All Songs',
      'folders': 'Folders',
      'ai_mixes': 'AI Mixes',
      'playing': 'Playing',
      'paused': 'Paused',
      'next': 'Next',
      'previous': 'Previous',
      'shuffle': 'Shuffle',
      'repeat': 'Repeat',
      'autoplay': 'Autoplay',
      'sleep_timer': 'Sleep Timer',
      'audio_output': 'Audio Output',
      'lyrics': 'Lyrics',
      'no_lyrics': 'No lyrics found',
      'loading': 'Loading...',
      'error': 'Something went wrong',
      'retry': 'Retry',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'rename': 'Rename',
      'add_to_queue': 'Add to Queue',
      'play_next': 'Play Next',
      'share': 'Share',
      'download': 'Download',
      'downloaded': 'Downloaded',
      'remove': 'Remove',
      'about': 'About',
      'version': 'Version',
      'developer': 'Developer',
    },
    'hi': {
      'lang_name': 'हिन्दी',
      'app_name': 'नोक्ट्रा',
      'good_morning': 'सुप्रभात',
      'good_afternoon': 'शुभ दोपहर',
      'good_evening': 'शुभ संध्या',
      'search_explore': 'खोजें और अन्वेषण करें',
      'library_title': 'लाइब्रेरी और स्टोरेज',
      'ai_studio_title': 'एआई साउंड स्टूडियो',
      'top_charts': 'ग्लोबल चार्ट्स',
      'create_folder': 'नया फ़ोल्डर बनाएं',
      'delete_folder': 'फ़ोल्डर हटाएं',
      'settings': 'सेटिंग्स और स्टोरेज',
      'party_mode': 'सिंककास्ट पार्टी मोड',
      'lossless_quality': 'मास्टर 320k तैयार',
      'recently_played': 'हाल ही में चलाया',
      'equalizer': 'इक्वलाइज़र FX',
      'developer_suite': 'डेवलपर सूट',
      'check_updates': 'अपडेट जांचें',
      'theme': 'थीम',
      'language': 'भाषा / Language',
      'home': 'होम',
      'search': 'खोजें',
      'library': 'लाइब्रेरी',
      'ai_studio': 'एआई स्टूडियो',
      'favorites': 'पसंदीदा',
      'downloads': 'डाउनलोड',
      'all_songs': 'सभी गाने',
      'folders': 'फ़ोल्डर',
      'ai_mixes': 'एआई मिक्स',
      'playing': 'चल रहा है',
      'paused': 'रुका हुआ',
      'next': 'अगला',
      'previous': 'पिछला',
      'shuffle': 'शफ़ल',
      'repeat': 'दोहराएं',
      'autoplay': 'ऑटोप्ले',
      'sleep_timer': 'स्लीप टाइमर',
      'audio_output': 'ऑडियो आउटपुट',
      'lyrics': 'गाने के बोल',
      'no_lyrics': 'बोल उपलब्ध नहीं',
      'loading': 'लोड हो रहा है...',
      'error': 'कुछ गलत हो गया',
      'retry': 'पुनः प्रयास करें',
      'cancel': 'रद्द करें',
      'save': 'सहेजें',
      'delete': 'हटाएं',
      'rename': 'नाम बदलें',
      'add_to_queue': 'कतार में जोड़ें',
      'play_next': 'अगला चलाएं',
      'share': 'साझा करें',
      'download': 'डाउनलोड',
      'downloaded': 'डाउनलोड हो गया',
      'remove': 'हटाएं',
      'about': 'परिचय',
      'version': 'संस्करण',
      'developer': 'डेवलपर',
    },
    'pa': {
      'lang_name': 'ਪੰਜਾਬੀ',
      'app_name': 'ਨੋਕਟ੍ਰਾ',
      'good_morning': 'ਸ਼ੁਭ ਸਵੇਰ',
      'good_afternoon': 'ਸ਼ੁਭ ਦੁਪਹਿਰ',
      'good_evening': 'ਸ਼ੁਭ ਸ਼ਾਮ',
      'search_explore': 'ਖੋਜੋ ਅਤੇ ਪਤਾ ਲਗਾਓ',
      'library_title': 'ਲਾਇਬ੍ਰੇਰੀ ਅਤੇ ਸਟੋਰੇਜ',
      'ai_studio_title': 'ਏਆਈ ਸਾਊਂਡ ਸਟੂਡੀਓ',
      'top_charts': 'ਗਲੋਬਲ ਚਾਰਟਸ',
      'create_folder': 'ਨਵਾਂ ਫੋਲਡਰ ਬਣਾਓ',
      'delete_folder': 'ਫੋਲਡਰ ਮਿਟਾਓ',
      'settings': 'ਸੈਟਿੰਗਾਂ ਅਤੇ ਸਟੋਰੇਜ',
      'party_mode': 'ਸਿੰਕਕਾਸਟ ਪਾਰਟੀ ਮੋਡ',
      'lossless_quality': 'ਮਾਸਟਰ 320k ਤਿਆਰ',
      'recently_played': 'ਹਾਲ ਹੀ ਵਿੱਚ ਚਲਾਇਆ',
      'equalizer': 'ਇਕੁਆਲਾਈਜ਼ਰ FX',
      'developer_suite': 'ਡਿਵੈਲਪਰ ਸੂਟ',
      'check_updates': 'ਅੱਪਡੇਟ ਜਾਂਚੋ',
      'theme': 'ਥੀਮ',
      'language': 'ਭਾਸ਼ਾ / Language',
      'home': 'ਹੋਮ',
      'search': 'ਖੋਜੋ',
      'library': 'ਲਾਇਬ੍ਰੇਰੀ',
      'ai_studio': 'ਏਆਈ ਸਟੂਡੀਓ',
      'favorites': 'ਪਸੰਦੀਦਾ',
      'downloads': 'ਡਾਊਨਲੋਡ',
      'all_songs': 'ਸਾਰੇ ਗਾਣੇ',
      'folders': 'ਫੋਲਡਰ',
      'ai_mixes': 'ਏਆਈ ਮਿਕਸ',
      'playing': 'ਚੱਲ ਰਿਹਾ ਹੈ',
      'paused': 'ਰੁਕਿਆ',
      'next': 'ਅਗਲਾ',
      'previous': 'ਪਿਛਲਾ',
      'shuffle': 'ਸ਼ਫਲ',
      'repeat': 'ਦੁਹਰਾਓ',
      'autoplay': 'ਆਟੋਪਲੇ',
      'sleep_timer': 'ਸਲੀਪ ਟਾਈਮਰ',
      'audio_output': 'ਆਡੀਓ ਆਊਟਪੁੱਟ',
      'lyrics': 'ਬੋਲ',
      'no_lyrics': 'ਬੋਲ ਉਪਲਬਧ ਨਹੀਂ',
      'loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
      'error': 'ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ',
      'retry': 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
      'cancel': 'ਰੱਦ ਕਰੋ',
      'save': 'ਸੰਭਾਲੋ',
      'delete': 'ਮਿਟਾਓ',
      'rename': 'ਨਾਮ ਬਦਲੋ',
      'add_to_queue': 'ਕਤਾਰ ਵਿੱਚ ਸ਼ਾਮਲ',
      'play_next': 'ਅਗਲਾ ਚਲਾਓ',
      'share': 'ਸਾਂਝਾ ਕਰੋ',
      'download': 'ਡਾਊਨਲੋਡ',
      'downloaded': 'ਡਾਊਨਲੋਡ ਹੋ ਗਿਆ',
      'remove': 'ਹਟਾਓ',
      'about': 'ਬਾਰੇ',
      'version': 'ਸੰਸਕਰਣ',
      'developer': 'ਡਿਵੈਲਪਰ',
    },
    'ur': {
      'lang_name': 'اردو',
      'app_name': 'نوکٹرا',
      'good_morning': 'صبح بخیر',
      'good_afternoon': 'دوپہر بخیر',
      'good_evening': 'شام بخیر',
      'search_explore': 'تلاش اور دریافت کریں',
      'library_title': 'لائبریری اور اسٹوریج',
      'ai_studio_title': 'اے آئی ساؤنڈ اسٹوڈیو',
      'top_charts': 'عالمی چارٹس',
      'create_folder': 'نیا فولڈر بنائیں',
      'delete_folder': 'فولڈر حذف کریں',
      'settings': 'ترتیبات اور اسٹوریج',
      'party_mode': 'سنک کاسٹ پارٹی موڈ',
      'lossless_quality': 'ماسٹر 320k تیار',
      'recently_played': 'حال ہی میں چلایا',
      'equalizer': 'ایکوالائزر FX',
      'developer_suite': 'ڈیویلپر سوٹ',
      'check_updates': 'اپ ڈیٹ چیک کریں',
      'theme': 'تھیم',
      'language': 'زبان / Language',
      'home': 'ہوم',
      'search': 'تلاش',
      'library': 'لائبریری',
      'ai_studio': 'اے آئی اسٹوڈیو',
      'favorites': 'پسندیدہ',
      'downloads': 'ڈاؤن لوڈ',
      'all_songs': 'تمام گانے',
      'folders': 'فولڈر',
      'ai_mixes': 'اے آئی مکس',
      'playing': 'چل رہا ہے',
      'paused': 'رکا ہوا',
      'next': 'اگلا',
      'previous': 'پچھلا',
      'shuffle': 'شفل',
      'repeat': 'دہرائیں',
      'autoplay': 'آٹو پلے',
      'sleep_timer': 'سلیپ ٹائمر',
      'audio_output': 'آڈیو آؤٹ پٹ',
      'lyrics': 'گانے کے بول',
      'no_lyrics': 'بول دستیاب نہیں',
      'loading': 'لوڈ ہو رہا ہے...',
      'error': 'کچھ غلط ہو گیا',
      'retry': 'دوبارہ کوشش کریں',
      'cancel': 'منسوخ کریں',
      'save': 'محفوظ کریں',
      'delete': 'حذف کریں',
      'rename': 'نام تبدیل کریں',
      'add_to_queue': 'قطار میں شامل',
      'play_next': 'اگلا چلائیں',
      'share': 'شیئر کریں',
      'download': 'ڈاؤن لوڈ',
      'downloaded': 'ڈاؤن لوڈ ہو گیا',
      'remove': 'ہٹائیں',
      'about': 'متعلق',
      'version': 'ورژن',
      'developer': 'ڈیویلپر',
    },
  };
}
