class NoctraLocalization {
  static String currentLanguage = 'en';

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'Noctra',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'search_explore': 'Search & Explore',
      'library_title': 'Library & Storage',
      'ai_studio_title': 'AI Sound Studio',
      'top_charts': 'Spotify Global Charts',
      'create_folder': 'Create New Folder',
      'delete_folder': 'Delete Folder',
      'settings': 'Settings & Storage',
      'party_mode': 'SyncCast Party Mode',
      'lossless_quality': 'Lossless 320k Ready',
    },
    'hi': {
      'app_name': 'नोक्ट्रा',
      'good_morning': 'सुप्रभात',
      'good_afternoon': 'शुभ दोपहर',
      'good_evening': 'शुभ संध्या',
      'search_explore': 'खोजें और अन्वेषण करें',
      'library_title': 'लाइब्रेरी और स्टोरेज',
      'ai_studio_title': 'एआई साउंड स्टूडियो',
      'top_charts': 'स्पॉटिफ़ाई ग्लोबल चार्ट्स',
      'create_folder': 'नया फ़ोल्डर बनाएं',
      'delete_folder': 'फ़ोल्डर हटाएं',
      'settings': 'सेटिंग्स और स्टोरेज',
      'party_mode': 'सिंककास्ट पार्टी मोड',
      'lossless_quality': 'लॉसलेस 320k तैयार',
    },
    'ur': {
      'app_name': 'نوکٹرا',
      'good_morning': 'صبح بخیر',
      'good_afternoon': 'دوپہر بخیر',
      'good_evening': 'شام بخیر',
      'search_explore': 'تلاش اور دریافت کریں',
      'library_title': 'لائبریری اور اسٹوریج',
      'ai_studio_title': 'اے آئی ساؤنڈ اسٹوڈیو',
      'top_charts': 'اسپاٹیفائی گلوبل چارٹس',
      'create_folder': 'نیا فولڈر بنائیں',
      'delete_folder': 'فولڈر حذف کریں',
      'settings': 'ترتیبات اور اسٹوریج',
      'party_mode': 'سنک کاسٹ پارٹی موڈ',
      'lossless_quality': 'لاس لیس 320k تیار',
    },
    'es': {
      'app_name': 'Noctra',
      'good_morning': 'Buenos Días',
      'good_afternoon': 'Buenas Tardes',
      'good_evening': 'Buenas Noches',
      'search_explore': 'Buscar y Explorar',
      'library_title': 'Biblioteca y Almacenamiento',
      'ai_studio_title': 'Estudio de Sonido IA',
      'top_charts': 'Listas Globales de Spotify',
      'create_folder': 'Crear Nueva Carpeta',
      'delete_folder': 'Eliminar Carpeta',
      'settings': 'Ajustes y Almacenamiento',
      'party_mode': 'Modo Fiesta SyncCast',
      'lossless_quality': 'Sin Pérdidas 320k Listo',
    },
    'fr': {
      'app_name': 'Noctra',
      'good_morning': 'Bonjour',
      'good_afternoon': 'Bon Après-midi',
      'good_evening': 'Bonsoir',
      'search_explore': 'Rechercher & Explorer',
      'library_title': 'Bibliothèque & Stockage',
      'ai_studio_title': 'Studio Sonore IA',
      'top_charts': 'Classements Mondiaux Spotify',
      'create_folder': 'Créer un Nouveau Dossier',
      'delete_folder': 'Supprimer le Dossier',
      'settings': 'Paramètres & Stockage',
      'party_mode': 'Mode Fête SyncCast',
      'lossless_quality': 'Qualité 320k Sans Perte',
    },
  };

  static String tr(String key) {
    return _localizedValues[currentLanguage]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}
