
/// Full i18n system for Noctra.
/// Supported: English, Hindi, Punjabi, Urdu, Kannada, Tamil, Marathi, Odia
class NoctraLocalization {
  static String currentLanguage = 'en';

  /// All supported languages with display names.
  static const Map<String, String> supportedLanguages = {
    'en': 'English',
    'hi': 'हिन्दी',
    'pa': 'ਪੰਜਾਬੀ',
    'ur': 'اردو',
    'kn': 'ಕನ್ನಡ',
    'ta': 'தமிழ்',
    'mr': 'मराठी',
    'or': 'ଓଡ଼ିଆ',
  };

  /// Language codes for the settings UI.
  static List<String> get availableLanguages =>
      supportedLanguages.keys.toList();

  /// Get display name for a language code.
  static String languageName(String code) =>
      _localizedValues[code]?['lang_name'] ??
      _localizedValues['en']?[code] ??
      code;

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'lang_name': 'English',
      'app_name': 'Noctra',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'search_explore': 'Search & Explore',
      'library_title': 'Library & Storage',
      'ai_studio_title': 'AI Sound Studio',
      'top_charts': 'Global Charts',
      'create_folder': 'Create New Folder',
      'delete_folder': 'Delete Folder',
      'settings': 'Settings & Storage',
      'party_mode': 'SyncCast Party Mode',
      'lossless_quality': 'Master 320k Ready',
      'recently_played': 'Recently Played',
      'equalizer': 'Equalizer FX',
      'developer_suite': 'Developer Suite',
      'check_updates': 'Check for Updates',
      'theme': 'Theme',
      'language': 'Language / भाषा',
      'home': 'Home',
      'search': 'Search',
      'library': 'Library',
      'ai_studio': 'AI Studio',
      'favorites': 'Favorites',
      'downloads': 'Downloads',
      'all_songs': 'All Songs',
      'folders': 'Folders',
      'ai_mixes': 'AI Mixes',
      'playing': 'Playing',
      'paused': 'Paused',
      'next': 'Next',
      'previous': 'Previous',
      'shuffle': 'Shuffle',
      'repeat': 'Repeat',
      'autoplay': 'Autoplay',
      'sleep_timer': 'Sleep Timer',
      'audio_output': 'Audio Output',
      'lyrics': 'Lyrics',
      'no_lyrics': 'No lyrics found',
      'loading': 'Loading...',
      'error': 'Something went wrong',
      'retry': 'Retry',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'rename': 'Rename',
      'add_to_queue': 'Add to Queue',
      'play_next': 'Play Next',
      'share': 'Share',
      'download': 'Download',
      'downloaded': 'Downloaded',
      'remove': 'Remove',
      'about': 'About',
      'version': 'Version',
      'developer': 'Developer',
    },
    'hi': {
      'lang_name': 'हिन्दी',
      'app_name': 'नोक्ट्रा',
      'good_morning': 'सुप्रभात',
      'good_afternoon': 'शुभ दोपहर',
      'good_evening': 'शुभ संध्या',
      'search_explore': 'खोजें और अन्वेषण करें',
      'library_title': 'लाइब्रेरी और स्टोरेज',
      'ai_studio_title': 'एआई साउंड स्टूडियो',
      'top_charts': 'ग्लोबल चार्ट्स',
      'create_folder': 'नया फ़ोल्डर बनाएं',
      'delete_folder': 'फ़ोल्डर हटाएं',
      'settings': 'सेटिंग्स और स्टोरेज',
      'party_mode': 'सिंककास्ट पार्टी मोड',
      'lossless_quality': 'मास्टर 320k तैयार',
      'recently_played': 'हाल ही में चलाया',
      'equalizer': 'इक्वलाइज़र FX',
      'developer_suite': 'डेवलपर सूट',
      'check_updates': 'अपडेट जांचें',
      'theme': 'थीम',
      'language': 'भाषा / Language',
      'home': 'होम',
      'search': 'खोजें',
      'library': 'लाइब्रेरी',
      'ai_studio': 'एआई स्टूडियो',
      'favorites': 'पसंदीदा',
      'downloads': 'डाउनलोड',
      'all_songs': 'सभी गाने',
      'folders': 'फ़ोल्डर',
      'ai_mixes': 'एआई मिक्स',
      'playing': 'चल रहा है',
      'paused': 'रुका हुआ',
      'next': 'अगला',
      'previous': 'पिछला',
      'shuffle': 'शफ़ल',
      'repeat': 'दोहराएं',
      'autoplay': 'ऑटोप्ले',
      'sleep_timer': 'स्लीप टाइमर',
      'audio_output': 'ऑडियो आउटपुट',
      'lyrics': 'गाने के बोल',
      'no_lyrics': 'बोल उपलब्ध नहीं',
      'loading': 'लोड हो रहा है...',
      'error': 'कुछ गलत हो गया',
      'retry': 'पुनः प्रयास करें',
      'cancel': 'रद्द करें',
      'save': 'सहेजें',
      'delete': 'हटाएं',
      'rename': 'नाम बदलें',
      'add_to_queue': 'कतार में जोड़ें',
      'play_next': 'अगला चलाएं',
      'share': 'साझा करें',
      'download': 'डाउनलोड',
      'downloaded': 'डाउनलोड हो गया',
      'remove': 'हटाएं',
      'about': 'परिचय',
      'version': 'संस्करण',
      'developer': 'डेवलपर',
    },
    'pa': {
      'lang_name': 'ਪੰਜਾਬੀ',
      'app_name': 'ਨੋਕਟ੍ਰਾ',
      'good_morning': 'ਸ਼ੁਭ ਸਵੇਰ',
      'good_afternoon': 'ਸ਼ੁਭ ਦੁਪਹਿਰ',
      'good_evening': 'ਸ਼ੁਭ ਸ਼ਾਮ',
      'search_explore': 'ਖੋਜੋ ਅਤੇ ਪਤਾ ਲਗਾਓ',
      'library_title': 'ਲਾਇਬ੍ਰੇਰੀ ਅਤੇ ਸਟੋਰੇਜ',
      'ai_studio_title': 'ਏਆਈ ਸਾਊਂਡ ਸਟੂਡੀਓ',
      'top_charts': 'ਗਲੋਬਲ ਚਾਰਟਸ',
      'create_folder': 'ਨਵਾਂ ਫੋਲਡਰ ਬਣਾਓ',
      'delete_folder': 'ਫੋਲਡਰ ਮਿਟਾਓ',
      'settings': 'ਸੈਟਿੰਗਾਂ ਅਤੇ ਸਟੋਰੇਜ',
      'party_mode': 'ਸਿੰਕਕਾਸਟ ਪਾਰਟੀ ਮੋਡ',
      'lossless_quality': 'ਮਾਸਟਰ 320k ਤਿਆਰ',
      'recently_played': 'ਹਾਲ ਹੀ ਵਿੱਚ ਚਲਾਇਆ',
      'equalizer': 'ਇਕੁਆਲਾਈਜ਼ਰ FX',
      'developer_suite': 'ਡਿਵੈਲਪਰ ਸੂਟ',
      'check_updates': 'ਅੱਪਡੇਟ ਜਾਂਚੋ',
      'theme': 'ਥੀਮ',
      'language': 'ਭਾਸ਼ਾ / Language',
      'home': 'ਹੋਮ',
      'search': 'ਖੋਜੋ',
      'library': 'ਲਾਇਬ੍ਰੇਰੀ',
      'ai_studio': 'ਏਆਈ ਸਟੂਡੀਓ',
      'favorites': 'ਪਸੰਦੀਦਾ',
      'downloads': 'ਡਾਊਨਲੋਡ',
      'all_songs': 'ਸਾਰੇ ਗਾਣੇ',
      'folders': 'ਫੋਲਡਰ',
      'ai_mixes': 'ਏਆਈ ਮਿਕਸ',
      'playing': 'ਚੱਲ ਰਿਹਾ ਹੈ',
      'paused': 'ਰੁਕਿਆ',
      'next': 'ਅਗਲਾ',
      'previous': 'ਪਿਛਲਾ',
      'shuffle': 'ਸ਼ਫਲ',
      'repeat': 'ਦੁਹਰਾਓ',
      'autoplay': 'ਆਟੋਪਲੇ',
      'sleep_timer': 'ਸਲੀਪ ਟਾਈਮਰ',
      'audio_output': 'ਆਡੀਓ ਆਊਟਪੁੱਟ',
      'lyrics': 'ਬੋਲ',
      'no_lyrics': 'ਬੋਲ ਉਪਲਬਧ ਨਹੀਂ',
      'loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
      'error': 'ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ',
      'retry': 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
      'cancel': 'ਰੱਦ ਕਰੋ',
      'save': 'ਸੰਭਾਲੋ',
      'delete': 'ਮਿਟਾਓ',
      'rename': 'ਨਾਮ ਬਦਲੋ',
      'add_to_queue': 'ਕਤਾਰ ਵਿੱਚ ਸ਼ਾਮਲ',
      'play_next': 'ਅਗਲਾ ਚਲਾਓ',
      'share': 'ਸਾਂਝਾ ਕਰੋ',
      'download': 'ਡਾਊਨਲੋਡ',
      'downloaded': 'ਡਾਊਨਲੋਡ ਹੋ ਗਿਆ',
      'remove': 'ਹਟਾਓ',
      'about': 'ਬਾਰੇ',
      'version': 'ਸੰਸਕਰਣ',
      'developer': 'ਡਿਵੈਲਪਰ',
    },
    'ur': {
      'lang_name': 'اردو',
      'app_name': 'نوکٹرا',
      'good_morning': 'صبح بخیر',
      'good_afternoon': 'دوپہر بخیر',
      'good_evening': 'شام بخیر',
      'search_explore': 'تلاش اور دریافت کریں',
      'library_title': 'لائبریری اور اسٹوریج',
      'ai_studio_title': 'اے آئی ساؤنڈ اسٹوڈیو',
      'top_charts': 'عالمی چارٹس',
      'create_folder': 'نیا فولڈر بنائیں',
      'delete_folder': 'فولڈر حذف کریں',
      'settings': 'ترتیبات اور اسٹوریج',
      'party_mode': 'سنک کاسٹ پارٹی موڈ',
      'lossless_quality': 'ماسٹر 320k تیار',
      'recently_played': 'حال ہی میں چلایا',
      'equalizer': 'ایکوالائزر FX',
      'developer_suite': 'ڈیویلپر سوٹ',
      'check_updates': 'اپ ڈیٹ چیک کریں',
      'theme': 'تھیم',
      'language': 'زبان / Language',
      'home': 'ہوم',
      'search': 'تلاش',
      'library': 'لائبریری',
      'ai_studio': 'اے آئی اسٹوڈیو',
      'favorites': 'پسندیدہ',
      'downloads': 'ڈاؤن لوڈ',
      'all_songs': 'تمام گانے',
      'folders': 'فولڈر',
      'ai_mixes': 'اے آئی مکس',
      'playing': 'چل رہا ہے',
      'paused': 'رکا ہوا',
      'next': 'اگلا',
      'previous': 'پچھلا',
      'shuffle': 'شفل',
      'repeat': 'دہرائیں',
      'autoplay': 'آٹو پلے',
      'sleep_timer': 'سلیپ ٹائمر',
      'audio_output': 'آڈیو آؤٹ پٹ',
      'lyrics': 'گانے کے بول',
      'no_lyrics': 'بول دستیاب نہیں',
      'loading': 'لوڈ ہو رہا ہے...',
      'error': 'کچھ غلط ہو گیا',
      'retry': 'دوبارہ کوشش کریں',
      'cancel': 'منسوخ کریں',
      'save': 'محفوظ کریں',
      'delete': 'حذف کریں',
      'rename': 'نام تبدیل کریں',
      'add_to_queue': 'قطار میں شامل',
      'play_next': 'اگلا چلائیں',
      'share': 'شیئر کریں',
      'download': 'ڈاؤن لوڈ',
      'downloaded': 'ڈاؤن لوڈ ہو گیا',
      'remove': 'ہٹائیں',
      'about': 'متعلق',
      'version': 'ورژن',
      'developer': 'ڈیویلپر',
    },
    'kn': {
      'lang_name': 'ಕನ್ನಡ',
      'app_name': 'ನೋಕ್ಟ್ರಾ',
      'good_morning': 'ಶುಭ ಬೆಳಿಗ್ಗೆ',
      'good_afternoon': 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
      'good_evening': 'ಶುಭ ಸಂಜೆ',
      'search_explore': 'ಹುಡುಕಿ ಮತ್ತು ಅನ್ವೇಷಿಸಿ',
      'library_title': 'ಲೈಬ್ರರಿ ಮತ್ತು ಸಂಗ್ರಹಣೆ',
      'ai_studio_title': 'AI ಧ್ವನಿ ಸ್ಟುಡಿಯೋ',
      'top_charts': 'ಜಾಗತಿಕ ಚಾರ್ಟ್‌ಗಳು',
      'create_folder': 'ಹೊಸ ಫೋಲ್ಡರ್ ರಚಿಸಿ',
      'delete_folder': 'ಫೋಲ್ಡರ್ ಅಳಿಸಿ',
      'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'party_mode': 'SyncCast ಪಾರ್ಟಿ ಮೋಡ್',
      'lossless_quality': 'ಮಾಸ್ಟರ್ 320k ಸಿದ್ಧ',
      'recently_played': 'ಇತ್ತೀಚೆಗೆ ಪ್ಲೇ ಮಾಡಿದ',
      'equalizer': 'ಈಕ್ವಲೈಜರ್ FX',
      'developer_suite': 'ಡೆವಲಪರ್ ಸೂಟ್',
      'check_updates': 'ಅಪ್‌ಡೇಟ್ ಪರಿಶೀಲಿಸಿ',
      'theme': 'ಥೀಮ್',
      'language': 'ಭಾಷೆ / Language',
      'home': 'ಹೋಮ್',
      'search': 'ಹುಡುಕಿ',
      'library': 'ಲೈಬ್ರರಿ',
      'ai_studio': 'AI ಸ್ಟುಡಿಯೋ',
      'favorites': 'ಮೆಚ್ಚಿದವು',
      'downloads': 'ಡೌನ್‌ಲೋಡ್‌ಗಳು',
      'all_songs': 'ಎಲ್ಲಾ ಹಾಡುಗಳು',
      'folders': 'ಫೋಲ್ಡರ್‌ಗಳು',
      'ai_mixes': 'AI ಮಿಕ್ಸ್',
      'playing': 'ಪ್ಲೇ ಆಗುತ್ತಿದೆ',
      'paused': 'ವಿರಾಮ',
      'next': 'ಮುಂದೆ',
      'previous': 'ಹಿಂದೆ',
      'shuffle': 'ಶಫಲ್',
      'repeat': 'ಪುನರಾವರ್ತನೆ',
      'autoplay': 'ಆಟೋಪ್ಲೇ',
      'sleep_timer': 'ಸ್ಲೀಪ್ ಟೈಮರ್',
      'audio_output': 'ಆಡಿಯೋ ಔಟ್‌ಪುಟ್',
      'lyrics': 'ಸಾಹಿತ್ಯ',
      'no_lyrics': 'ಸಾಹಿತ್ಯ ಲಭ್ಯವಿಲ್ಲ',
      'loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
      'error': 'ಏನೋ ತಪ್ಪಾಗಿದೆ',
      'retry': 'ಮರುಪ್ರಯತ್ನಿಸಿ',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'save': 'ಉಳಿಸಿ',
      'delete': 'ಅಳಿಸಿ',
      'rename': 'ಹೆಸರು ಬದಲಾಯಿಸಿ',
      'add_to_queue': 'ಕ್ಯೂಗೆ ಸೇರಿಸಿ',
      'play_next': 'ಮುಂದೆ ಪ್ಲೇ ಮಾಡಿ',
      'share': 'ಹಂಚಿಕೊಳ್ಳಿ',
      'download': 'ಡೌನ್‌ಲೋಡ್',
      'downloaded': 'ಡೌನ್‌ಲೋಡ್ ಆಗಿದೆ',
      'remove': 'ತೆಗೆದುಹಾಕಿ',
      'about': 'ಕುರಿತು',
      'version': 'ಆವೃತ್ತಿ',
      'developer': 'ಡೆವಲಪರ್',
    },
    'ta': {
      'lang_name': 'தமிழ்',
      'app_name': 'நோக்ட்ரா',
      'good_morning': 'காலை வணக்கம்',
      'good_afternoon': 'மதிய வணக்கம்',
      'good_evening': 'மாலை வணக்கம்',
      'search_explore': 'தேடி ஆராயுங்கள்',
      'library_title': 'நூலகம் மற்றும் சேமிப்பு',
      'ai_studio_title': 'AI ஒலி ஸ்டுடியோ',
      'top_charts': 'உலக சார்ட்கள்',
      'create_folder': 'புதிய கோப்புறை உருவாக்கு',
      'delete_folder': 'கோப்புறை நீக்கு',
      'settings': 'அமைப்புகள்',
      'party_mode': 'SyncCast கட்சி பயன்முறை',
      'lossless_quality': 'மாஸ்டர் 320k தயார்',
      'recently_played': 'சமீபத்தில் இயக்கப்பட்டது',
      'equalizer': 'குறுங்காணி FX',
      'developer_suite': 'உருவாக்குநர் ஸ்வீட்',
      'check_updates': 'புதுப்பிப்பு சரிபார்',
      'theme': 'தீம்',
      'language': 'மொழி / Language',
      'home': 'முகப்பு',
      'search': 'தேடு',
      'library': 'நூலகம்',
      'ai_studio': 'AI ஸ்டுடியோ',
      'favorites': 'விருப்பங்கள்',
      'downloads': 'பதிவிறக்கங்கள்',
      'all_songs': 'அனைத்து பாடல்கள்',
      'folders': 'கோப்புறைகள்',
      'ai_mixes': 'AI கலவைகள்',
      'playing': 'இயக்கப்படுகிறது',
      'paused': 'இடைநிறுத்தப்பட்டது',
      'next': 'அடுத்து',
      'previous': 'முந்தைய',
      'shuffle': 'கலக்கவும்',
      'repeat': 'மீண்டும்',
      'autoplay': 'தானியங்கு',
      'sleep_timer': 'தூக்க டைமர்',
      'audio_output': 'ஆடியோ வெளியீடு',
      'lyrics': 'பாடல் வரிகள்',
      'no_lyrics': 'வரிகள் கிடைக்கவில்லை',
      'loading': 'ஏற்றுகிறது...',
      'error': 'ஏதோ தவறு நடந்தது',
      'retry': 'மீண்டும் முயற்சி',
      'cancel': 'ரத்து',
      'save': 'சேமி',
      'delete': 'நீக்கு',
      'rename': 'மறுபெயரிடு',
      'add_to_queue': 'வரிசையில் சேர்',
      'play_next': 'அடுத்து இயக்கு',
      'share': 'பகிர்',
      'download': 'பதிவிறக்கு',
      'downloaded': 'பதிவிறக்கப்பட்டது',
      'remove': 'நீக்கு',
      'about': 'பற்றி',
      'version': 'பதிப்பு',
      'developer': 'உருவாக்குநர்',
    },
    'mr': {
      'lang_name': 'मराठी',
      'app_name': 'नोक्ट्रा',
      'good_morning': 'सुप्रभात',
      'good_afternoon': 'शुभ दुपार',
      'good_evening': 'शुभ संध्या',
      'search_explore': 'शोधा आणि शोधा',
      'library_title': 'लायब्ररी आणि स्टोरेज',
      'ai_studio_title': 'एआय साऊंड स्टुडिओ',
      'top_charts': 'जागतिक चार्ट्स',
      'create_folder': 'नवीन फोल्डर तयार करा',
      'delete_folder': 'फोल्डर हटवा',
      'settings': 'सेटिंग्ज',
      'party_mode': 'SyncCast पार्टी मोड',
      'lossless_quality': 'मास्टर 320k तयार',
      'recently_played': 'अलीकडचे वाजवलेले',
      'equalizer': 'इक्वलायझर FX',
      'developer_suite': 'विकासक सुट',
      'check_updates': 'अपडेट तपासा',
      'theme': 'थीम',
      'language': 'भाषा / Language',
      'home': 'होम',
      'search': 'शोधा',
      'library': 'लायब्ररी',
      'ai_studio': 'एआय स्टुडिओ',
      'favorites': 'आवडते',
      'downloads': 'डाउनलोड',
      'all_songs': 'सर्व गाणी',
      'folders': 'फोल्डर',
      'ai_mixes': 'एआय मिक्स',
      'playing': 'वाजत आहे',
      'paused': 'थांबलेले',
      'next': 'पुढील',
      'previous': 'मागील',
      'shuffle': 'शफल',
      'repeat': 'पुनरावृत्ती',
      'autoplay': 'ऑटोप्ले',
      'sleep_timer': 'स्लीप टायमर',
      'audio_output': 'ऑडिओ आउटपुट',
      'lyrics': 'बोल',
      'no_lyrics': 'बोल उपलब्ध नाहीत',
      'loading': 'लोड होत आहे...',
      'error': 'काहीतरी चूक झाली',
      'retry': 'पुन्हा प्रयत्न करा',
      'cancel': 'रद्द करा',
      'save': 'जतन करा',
      'delete': 'हटवा',
      'rename': 'नाव बदला',
      'add_to_queue': 'रांगेत जोडा',
      'play_next': 'पुढील वाजवा',
      'share': 'शेअर करा',
      'download': 'डाउनलोड',
      'downloaded': 'डाउनलोड झाले',
      'remove': 'काढा',
      'about': 'बद्दल',
      'version': 'आवृत्ती',
      'developer': 'विकासक',
    },
    'or': {
      'lang_name': 'ଓଡ଼ିଆ',
      'app_name': 'ନୋକ୍ଟ୍ରା',
      'good_morning': 'ସୁପ୍ରଭାତ',
      'good_afternoon': 'ଶୁଭ ଅପରାହ୍ନ',
      'good_evening': 'ଶୁଭ ସନ୍ଧ୍ୟା',
      'search_explore': 'ଖୋଜନ୍ତୁ ଏବଂ ଅନୁସନ୍ଧାନ କରନ୍ତୁ',
      'library_title': 'ଲାଇବ୍ରେରୀ ଏବଂ ସ୍ଟୋରେଜ',
      'ai_studio_title': 'AI ସାଉଣ୍ଡ ଷ୍ଟୁଡିଓ',
      'top_charts': 'ଗ୍ଲୋବାଲ୍ ଚାର୍ଟସ୍',
      'create_folder': 'ନୂଆ ଫୋଲ୍ଡର ସୃଷ୍ଟି କରନ୍ତୁ',
      'delete_folder': 'ଫୋଲ୍ଡର ବିଲୋପ କରନ୍ତୁ',
      'settings': 'ସେଟିଂସ୍',
      'party_mode': 'SyncCast ପାର୍ଟି ମୋଡ୍',
      'lossless_quality': 'ମାଷ୍ଟର 320k ପ୍ରସ୍ତୁତ',
      'recently_played': 'ସାମ୍ପ୍ରତିକ ଚାଲିଥିବା',
      'equalizer': 'ଇକ୍ୱାଲାଇଜର FX',
      'developer_suite': 'ଡେଭେଲପର ସୁଟ୍',
      'check_updates': 'ଅପଡେଟ୍ ଯାଞ୍ଚ କରନ୍ତୁ',
      'theme': 'ଥିମ୍',
      'language': 'ଭାଷା / Language',
      'home': 'ହୋମ୍',
      'search': 'ଖୋଜନ୍ତୁ',
      'library': 'ଲାଇବ୍ରେରୀ',
      'ai_studio': 'AI ଷ୍ଟୁଡିଓ',
      'favorites': 'ପସନ୍ଦ',
      'downloads': 'ଡାଉନଲୋଡ୍',
      'all_songs': 'ସମସ୍ତ ଗୀତ',
      'folders': 'ଫୋଲ୍ଡର',
      'ai_mixes': 'AI ମିକ୍ସ',
      'playing': 'ଚାଲୁଛି',
      'paused': 'ଥାମିଛି',
      'next': 'ପରବର୍ତ୍ତୀ',
      'previous': 'ପୂର୍ବବର୍ତ୍ତୀ',
      'shuffle': 'ଶଫଲ୍',
      'repeat': 'ପୁନରାବୃତ୍ତି',
      'autoplay': 'ସ୍ୱୟଂଚାଳିତ',
      'sleep_timer': 'ନିଦ୍ରା ଟାଇମର୍',
      'audio_output': 'ଅଡିଓ ଆଉଟପୁଟ୍',
      'lyrics': 'ଗୀତ ବୋଲ',
      'no_lyrics': 'ବୋଲ ଉପଲବ୍ଧ ନାହିଁ',
      'loading': 'ଲୋଡ୍ ହେଉଛି...',
      'error': 'କିଛି ଭୁଲ୍ ହୋଇଛି',
      'retry': 'ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ',
      'cancel': 'ବାତିଲ୍ କରନ୍ତୁ',
      'save': 'ସଞ୍ଚୟ କରନ୍ତୁ',
      'delete': 'ବିଲୋପ କରନ୍ତୁ',
      'rename': 'ନାମ ପରିବର୍ତ୍ତନ କରନ୍ତୁ',
      'add_to_queue': 'ଧାଡ଼ିରେ ଯୋଗ କରନ୍ତୁ',
      'play_next': 'ପରବର୍ତ୍ତୀ ଚାଳନ୍ତୁ',
      'share': 'ସେୟାର କରନ୍ତୁ',
      'download': 'ଡାଉନଲୋଡ୍',
      'downloaded': 'ଡାଉନଲୋଡ୍ ହୋଇଛି',
      'remove': 'ହଟାନ୍ତୁ',
      'about': 'ବିଷୟରେ',
      'version': 'ସଂସ୍କରଣ',
      'developer': 'ଡେଭେଲପର୍',
    },
  };

  static String tr(String key) {
    return _localizedValues[currentLanguage]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}
