#!/usr/bin/env python3
"""Strict ≤ 300 LOC enforcement for Noctra.

Walks the Dart (lib/, test/) and Android (android/) source trees and
fails the build when any single source file exceeds the project's
hard 300 lines-of-code limit. The check is intentionally cheap so it
can run on every save or in CI without a Flutter dependency.

Usage:
  python tool/loc_guard.py            # check the whole project
  python tool/loc_guard.py --warn     # exit 0, but print offenders
  python tool/loc_guard.py --limit N  # override the cap (default 300)

Excluded paths (build artifacts, generated code, vendored deps):
  - **/build/**
  - **/.gradle/**
  - **/.idea/**
  - **/.dart_tool/**
  - **/.kotlin/**
  - **/.pub-cache/**

The script is platform-agnostic: it walks using os.walk and reads
files as UTF-8. Line counting is strict newline counting, matching
what CI tools like cloc and the Dart linter will report.
"""
from __future__ import annotations

import argparse
import os
import sys
from typing import Iterable, List, Tuple

DEFAULT_LIMIT = 300

# (root, included_extensions) pairs.
ROOTS: Tuple[Tuple[str, Tuple[str, ...]], ...] = (
    ("lib", (".dart",)),
    ("test", (".dart",)),
    # android/app/src/main source roots. build/, .gradle/ are excluded
    # by the path filter below.
    ("android", (".kt", ".java")),
    ("android/app", (".kts", ".gradle")),
)

EXCLUDE_DIR_NAMES = {
    "build", ".gradle", ".idea", ".dart_tool", ".kotlin", ".pub-cache",
    "node_modules", "Pods", ".venv", "venv", "__pycache__",
}

# A file extension is only counted as a "source" file we care about.
# We intentionally ignore .gradle inside android/ sub-modules because
# those are generated by Flutter's plugin tooling.
SOURCE_EXTENSIONS = {".dart", ".kt", ".java", ".kts"}


def _should_skip_dir(dirname: str) -> bool:
    return dirname in EXCLUDE_DIR_NAMES or dirname.startswith(".")


def _is_source_file(filename: str) -> bool:
    _, ext = os.path.splitext(filename)
    return ext in SOURCE_EXTENSIONS


def _walk_sources(project_root: str) -> Iterable[str]:
    for relative_root, _exts in ROOTS:
        absolute_root = os.path.join(project_root, relative_root)
        if not os.path.isdir(absolute_root):
            continue
        for dirpath, dirnames, filenames in os.walk(absolute_root):
            # Prune excluded directories in-place so os.walk skips them.
            dirnames[:] = [d for d in dirnames if not _should_skip_dir(d)]
            for filename in filenames:
                if not _is_source_file(filename):
                    continue
                yield os.path.join(dirpath, filename)


def _count_lines(path: str) -> int:
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        return sum(1 for _ in fh)


def _relpath(path: str, project_root: str) -> str:
    return os.path.relpath(path, project_root).replace(os.sep, "/")


def find_violations(
    project_root: str, limit: int
) -> List[Tuple[str, int]]:
    """Return (relpath, lines) tuples for files over the LOC limit."""
    offenders: List[Tuple[str, int]] = []
    for path in _walk_sources(project_root):
        lines = _count_lines(path)
        if lines > limit:
            offenders.append((_relpath(path, project_root), lines))
    offenders.sort(key=lambda t: (-t[1], t[0]))
    return offenders


def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Enforce the ≤ 300 LOC rule on Noctra source files.",
    )
    parser.add_argument(
        "--limit", type=int, default=DEFAULT_LIMIT,
        help="Maximum allowed lines per file (default: 300).",
    )
    parser.add_argument(
        "--warn", action="store_true",
        help="Report offenders but exit 0 (useful for local pre-commit).",
    )
    parser.add_argument(
        "--root", default=".",
        help="Project root (default: current directory).",
    )
    args = parser.parse_args(argv)

    project_root = os.path.abspath(args.root)
    offenders = find_violations(project_root, args.limit)

    if not offenders:
        print(
            f"loc_guard: all source files are <= {args.limit} LOC [OK]",
        )
        return 0

    print(
        f"loc_guard: {len(offenders)} file(s) exceed {args.limit} LOC:",
        file=sys.stderr,
    )
    for relpath, lines in offenders:
        print(f"  {lines:>4}  {relpath}", file=sys.stderr)

    if args.warn:
        print(
            "\n--warn set: exiting 0. Run without --warn to fail.",
            file=sys.stderr,
        )
        return 0

    print(
        "\nFix by decomposing the file into smaller parts/extensions "
        "(see ARCHITECTURE.md, §2 'Strict Modular Architecture').",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
